# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# Deploy to AWS S3 by schedule
name: Deploy to AWS S3 by schedule

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
        # Config AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

        # Setup java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Set up timezone
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
        timezone: Asia/Saigon

        # Run test and generate result
      - name: Run test
        run: mvn clean test -D headless=true
        continue-on-error: true

        # Caching
      - name: Cache Maven Packages
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

        # Push to S3
      - name: Push to S3 bucket
        run: aws s3 sync ./target/cucumber-html-reports/ s3://${GITHUB_REF##*/}-test.amperfii.io/$(date '+%Y-%m-%d_%H:%M:%S') --delete
